name: Pypy tests

on:
  push:
    paths:
      - '.github/workflows/pypy.yml'
      - '**.py'
      - '../../dev-requirements.txt'

jobs:
  test_pypy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python pypy3.12
      uses: actions/setup-python@v4
      with:
        python-version: pypy3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pypy lints and tests
      run: |
        make test_flake8 test_pylint test_pytest test_doctest test_other
